"""initial migrations

Revision ID: c59e46aa8560
Revises: 31783e2b0da0
Create Date: 2024-09-26 14:26:00.205693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59e46aa8560'
down_revision: Union[str, None] = '31783e2b0da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('des', sa.String(length=50), nullable=True),
    sa.Column('is_individual_group', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('sender_id', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=20), nullable=True),
    sa.Column('is_conection_req', sa.Boolean(), nullable=True),
    sa.Column('is_any_event', sa.Boolean(), nullable=True),
    sa.Column('msg', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_groups',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups')
    op.drop_table('chats')
    op.drop_table('groups')
    op.drop_table('users')
    # ### end Alembic commands ###
